---
name: Upload build
on:
  release:
    types:
      - published

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs:
      - build

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download Disk Image
        uses: actions/download-artifact@v4
        with:
          name: disk-image

      - name: Upload release artifact
        run: |
          gh release upload ${{github.event.release.tag_name}} monster-attack.d64
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
